name: valence_flutter
description: "A new Flutter package project."
version: 1.0.0
# homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  valence: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
